### ISSUE TITLE
id being used as a parameter name

### ISSUE THREAD

**Issue by Midar** [devkitPro/libctru#462]
It seems that recently a new release of ctrulib made it into devkitPro. Unfortunately, this broke Objective-C code, as now id - the type for "any object" in Objective-C - is used as a parameter name, meaning Objective-C code that includes <3ds.h> fails to compile.

Could this please be changed to something else? E.g. ID would be fine.

**Comment by WinterMute** [comment]
What specifically is causing this to fail?

**Comment by Midar** [comment]
```
In file included from /opt/devkitpro/libctru/include/3ds.h:62,
                 from OFDNSResolverSettings.m:45:
/opt/devkitpro/libctru/include/3ds/services/ptmsysm.h: In function 'ptmSysmGetNotificationAckValue':
/opt/devkitpro/libctru/include/3ds/services/ptmsysm.h:37:54: error: declaration of 'id' shadows a global declaration [-Werror=shadow]
   37 | static inline s32 ptmSysmGetNotificationAckValue(u32 id)
      |                                                  ~~~~^~
In file included from macros.h:43,
                 from OFObject.h:35,
                 from OFDNSResolverSettings.h:18,
                 from OFDNSResolverSettings.m:22:
runtime/ObjFWRT.h:62:29: note: shadowed declaration is here
   62 | typedef struct objc_object *id;
      |                             ^~
```

**Comment by Midar** [comment]
Note: The same can be achieved by #include <objc/objc.h> instead. id is a reserved identifier in ObjC and only the runtime must typedef it.

**Comment by WinterMute** [comment]
Being honest @Midar it's probably best if you PR something that fixes your issue. None of us are familiar enough with objective C to be sure we'll sort it.

**Comment by Midar** [comment]
There isn't much to do, just rename that argument from `id` to something else, e.g. `__id` (`__` is reserved for libc and e.g. glibc uses it everywhere), or do just `ID`. glibc seems to prefer to prefix everything with `__` to avoid any conflicts.

**Comment by WinterMute** [comment]
again, if you want this fixed please make a PR. We have other stuff to be getting on with and no means to test objective C.

**Comment by fincs** [comment]
I don't understand why only ptmSysmGetNotificationAckValue is an issue for you. Previously there have been countless instances of bare `id` used as a field/parameter name, in headers that have been in libctru for a long time such as the NDSP ones. What exactly are you doing to trigger this problem only now and not back then?

**Comment by Midar** [comment]
There's nothing I'm triggering now but not back then - my code is unchanged. All I did was update devkitARM. I worked around this by redefining id to id_3ds and then undefining it after including <3ds.h> and that works, but, is of course a nasty hack.

**Comment by Oreo639** [comment]
There are other instances of the variable name `id` being used but I can't find another one that is `static inline`. (not sure if that makes a difference as I don't do obj-c)

Having the variable name of `ID` (in all caps) seems out of place and out of style. Maybe notifId, notifID, or notif_id would be better.

**Comment by Midar** [comment]
Yeah, it's because it's in that static inline :). ObjC is just C in this case, with id just being a reserved name.

**Comment by fincs** [comment]
For anyone interested, the full list of files which use `id` as an identifier is as follows:

- svc.h
- shaderProgram.h (within gpu)
- shbin.h (within gpu)
- channel.h (within ndsp)
- ndsp.h (within ndsp)
- apt.h (within services)
- fs.h (within services)
- fspxi.h (within services)
- gspgpu.h (within services)
- hid.h (within services)
- nfc.h (within services)
- ptmsysm.h (within services)

Originally I was inclined to do a quick fix since it appeared there was only one instance of it causing trouble. However this turns out to be way more pervasive than originally anticipated. We don't really develop libraries with languages other than C/C++ in mind, and I'm not sure if making such sweeping changes is justified for a use case that isn't really supported.

On the other hand, going by the original error message posted, it looks like it might be possible to work around the issue by including libctru headers prior to including system Obj-C headers (assuming those exist, given the error message).
