### ISSUE TITLE
error language wrong

### ISSUE THREAD

**Issue by BlyZeDev** [devkitPro/libctru#552]
### What's the issue you encountered?

When I'm using the error appled the wrong language is diplayed for some reason.
CFG_LANGUAGE_DE gives me French.
CFG_LANGUAGE_FR gives me English.
CFG_LANGUAGE_EN gives me English as well.

### How can the issue be reproduced?

```c
errorConf conf;
errorInit(&conf, ERROR_TEXT_LANGUAGE_WORD_WRAP, CFG_LANGUAGE_DE); //Should be in german, but isn't
errorCode(&conf, code);
errorText(&conf, buffer);
errorDisp(&conf);
```

### Environment?

- Windows 11
- Official release, newest version

**Comment by BlyZeDev** [comment]
Update: I'm getting german with CFG_LANGUAGE_JP

**Comment by BlyZeDev** [comment]
When I use ERROR_TEXT flag in errorInit it works perfectly fine

**Comment by BlyZeDev** [comment]
```c
errorConf conf;
errorInit(&conf, ERROR_TEXT, CFG_LANGUAGE_DE); //Works perfectly
errorCode(&conf, code);
errorText(&conf, buffer);
errorDisp(&conf);
```

I think it may be something wrong with the flags.

**Comment by WinterMute** [comment]
> ```c
> errorConf conf;
> errorInit(&conf, ERROR_TEXT, CFG_LANGUAGE_DE); //Works perfectly
> errorCode(&conf, code);
> errorText(&conf, buffer);
> errorDisp(&conf);
> ```
> 
> I think it could be something wrong with the flags.

This isn't doing what you think it's doing. ERROR_TEXT doesn't have the language flag set so it's ignoring the language you pass and using the system language - in your case German it seems. If you use ERROR_TEXT_LANGUAGE you'll end up with the same symptoms.

https://github.com/devkitPro/libctru/pull/553 adds CFG_LANGUAGE_DEFAULT and passes lang + 1 to the system which makes the function behave as expected. Being honest though it seems to me that leaving the language flag unset so errors are displayed in the system language would be a better practice rather than explicitly using a language the user may not speak.

**Comment by BlyZeDev** [comment]
I used it like that, because I didn't know passing nothing would use System Language
```C
CFG_Language getSystemLang()
{
    u8 language;
    CFGU_GetSystemLanguage(&language);

    return language;
}
...
errorInit(&conf, ERROR_TEXT_LANGUAGE_WORD_WRAP, getSystemLang());
...
```
